FROM node:22-alpine

WORKDIR /app

# Install md5sum utility and ensure npm is available
RUN apk add --no-cache coreutils && \
    apk add --no-cache --update nodejs npm && \
    rm -rf /var/cache/apk/* && \
    npm -v && node -v

# Install additional dependencies for jsdom
RUN apk add --no-cache python3 make g++ \
    && rm -rf /var/cache/apk/*

# Don't run npm install in the Dockerfile
# We'll handle it in an entrypoint script instead

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 3000

ENV FAST_REFRESH=true
ENV TSC_COMPILE_ON_ERROR=true
ENV ESLINT_NO_DEV_ERRORS=true
ENV CHOKIDAR_USEPOLLING=true
ENV WDS_SOCKET_PORT=0
# Set Node memory limit
ENV NODE_OPTIONS="--max-old-space-size=4096"

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npm", "start"]