FROM node:18-alpine

WORKDIR /app

# Install md5sum utility
RUN apk add --no-cache coreutils

# Don't run npm install in the Dockerfile
# We'll handle it in an entrypoint script instead

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 3000

ENV FAST_REFRESH=true
ENV TSC_COMPILE_ON_ERROR=true
ENV ESLINT_NO_DEV_ERRORS=true
ENV CHOKIDAR_USEPOLLING=true
ENV WDS_SOCKET_PORT=0

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npm", "start"]