version: '3'

tasks:
  test:
    desc: Run frontend tests
    cmds:
      - echo "Running frontend tests..."
      - docker-compose -f {{.ROOT_DIR}}/docker-compose.{{.ENV}}.yml run --rm frontend npm test
    vars:
      ENV: '{{.ENV | default "dev"}}'
      ROOT_DIR: '{{.ROOT_DIR | default ".."}}'

  lint:
    desc: Run frontend linting
    cmds:
      - echo "Running frontend linting..."
      - docker-compose -f {{.ROOT_DIR}}/docker-compose.{{.ENV}}.yml run --rm frontend npm run lint
    vars:
      ENV: '{{.ENV | default "dev"}}'
      ROOT_DIR: '{{.ROOT_DIR | default ".."}}'

  lint-fix:
    desc: Fix frontend linting issues
    cmds:
      - echo "Running frontend linting with auto-fix..."
      - docker-compose -f {{.ROOT_DIR}}/docker-compose.{{.ENV}}.yml run --rm frontend npm run lint:fix
    vars:
      ENV: '{{.ENV | default "dev"}}'
      ROOT_DIR: '{{.ROOT_DIR | default ".."}}'

  shell:
    desc: Open shell in frontend container
    cmds:
      - docker-compose -f {{.ROOT_DIR}}/docker-compose.{{.ENV}}.yml exec frontend sh
    vars:
      ENV: '{{.ENV | default "dev"}}'
      ROOT_DIR: '{{.ROOT_DIR | default ".."}}'

  deps:update:
    desc: Update frontend dependencies
    cmds:
      - echo "Updating frontend dependencies..."
      - docker-compose -f {{.ROOT_DIR}}/docker-compose.{{.ENV}}.yml run --rm frontend npm update
      - docker-compose -f {{.ROOT_DIR}}/docker-compose.{{.ENV}}.yml run --rm frontend npm audit fix
    vars:
      ENV: '{{.ENV | default "dev"}}'
      ROOT_DIR: '{{.ROOT_DIR | default ".."}}'

  security:
    desc: Run frontend security audit
    cmds:
      - echo "Running frontend security audit..."
      - docker-compose -f {{.ROOT_DIR}}/docker-compose.{{.ENV}}.yml run --rm frontend npm audit
    vars:
      ENV: '{{.ENV | default "dev"}}'
      ROOT_DIR: '{{.ROOT_DIR | default ".."}}'

  build:
    desc: Build frontend for production
    cmds:
      - echo "Building frontend..."
      - docker-compose -f {{.ROOT_DIR}}/docker-compose.{{.ENV}}.yml run --rm frontend npm run build
    vars:
      ENV: '{{.ENV | default "dev"}}'
      ROOT_DIR: '{{.ROOT_DIR | default ".."}}'
