apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cat-weight-tracker
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cat-weight-tracker
spec:
  replicas: 2