apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-weight-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/cat-weight-tracker.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: cat-weight-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true