### This file contains REST API examples for interacting with MCP servers
### Install the "REST Client" VS Code extension to use this file

### Atlassian MCP API Examples

# Get Atlassian Jira server info
GET {{atlassianUrl}}/rest/api/2/serverInfo
Content-Type: application/json

### GitHub MCP API Examples

# Get GitHub API info
GET {{githubUrl}}/api/v3/meta
Content-Type: application/json

### Local API Examples

# Get all cats
GET {{baseUrl}}/cats/
Content-Type: application/json