### This file contains REST API examples for interacting with MCP servers
### Install the "REST Client" VS Code extension to use this file

### Jira API Examples

# Get Jira server info
GET {{jiraUrl}}/rest/api/2/serverInfo
Content-Type: application/json

### GitHub Alternative (Gogs) API Examples

# Get Gogs API info
GET {{githubUrl}}/api/v1/version
Content-Type: application/json

### Local API Examples

# Get all cats
GET {{baseUrl}}/cats/
Content-Type: application/json