---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cat-weight-tracker
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/sdcarter/cat-weight-tracker-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /cats/
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /cats/
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 30
        command: ["/bin/bash", "-c"]
        args:
          - |
            sleep 5 &&
            alembic upgrade head &&
            uvicorn app.main:app --host 0.0.0.0 --port 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cat-weight-tracker
  annotations:
    cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: backend