---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cat-weight-tracker
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        deployment.kubernetes.io/revision: "${TIMESTAMP}"
    spec:
      containers:
      - name: frontend
        image: sdcarter/cat-weight-tracker-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "/api"
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cat-weight-tracker
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend