apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-config
  namespace: cat-weight-tracker
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 80