apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cat-weight-tracker-gateway
  namespace: cat-weight-tracker
  annotations:
    networking.gke.io/health-check-port: "80"
    networking.gke.io/health-check-path: "/"
    networking.gke.io/v1beta1.BackendConfig: '{"default": {"healthCheck": {"checkIntervalSec": 15, "timeoutSec": 5, "healthyThreshold": 1, "unhealthyThreshold": 2, "type": "HTTP", "requestPath": "/", "port": 80}}}'
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: cat-weight-tracker-routes
  namespace: cat-weight-tracker
spec:
  parentRefs:
  - name: cat-weight-tracker-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: backend
      port: 4000
      kind: Service
      group: ""
      filters:
      - type: HealthCheck
        healthCheck:
          path: /cats/
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend
      port: 80
      kind: Service
      group: ""