apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cat-weight-tracker-ingress
  namespace: cat-weight-tracker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: cat-weight-tracker.local
    http:
      paths:
      - path: /api/?(.*)
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 4000
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80