apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - gateway.yaml
  - backend-config.yaml
  - frontend-config.yaml
  - health-check-policy.yaml