name: Build and Push Images

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/build-push.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Generate version tag
        id: version
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"
          
      - name: Create version file
        run: |
          echo "${{ steps.version.outputs.VERSION }}" > version.txt
          
      - name: Upload version artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-version
          path: version.txt
          retention-days: 1

  build-backend:
    needs: generate-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cat-weight-tracker-backend:${{ needs.generate-version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cat-weight-tracker-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-frontend:
    needs: generate-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cat-weight-tracker-frontend:${{ needs.generate-version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cat-weight-tracker-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
