name: Build and Push Images

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/build-push.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-backend
            ghcr.io/${{ github.repository }}-frontend

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cat-weight-tracker-backend:latest
            ghcr.io/${{ github.repository_owner }}/cat-weight-tracker-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cat-weight-tracker-frontend:latest
            ghcr.io/${{ github.repository_owner }}/cat-weight-tracker-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update image tags in Kubernetes manifests
        run: |
          echo "Updating image tags to ${{ github.sha }}"
          sed -i "s|ghcr.io/sdcarter/cat-weight-tracker-backend:latest|ghcr.io/${{ github.repository_owner }}/cat-weight-tracker-backend:${{ github.sha }}|g" k8s/base/backend.yaml
          sed -i "s|ghcr.io/sdcarter/cat-weight-tracker-frontend:latest|ghcr.io/${{ github.repository_owner }}/cat-weight-tracker-frontend:${{ github.sha }}|g" k8s/base/frontend.yaml
          
      - name: Commit and push updated manifests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add k8s/base/backend.yaml k8s/base/frontend.yaml
          git commit -m "chore: update image tags to ${{ github.sha }}" || echo "No changes to commit"
          git push