name: Deploy to GCP Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Images"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Configure kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Update Kubernetes manifests
        run: |
          # Use latest tag instead of commit SHA
          sed -i "s|ghcr.io/sdcarter/cat-weight-tracker-backend:latest|${{ secrets.DOCKERHUB_USERNAME }}/cat-weight-tracker-backend:latest|g" k8s/base/backend.yaml
          sed -i "s|ghcr.io/sdcarter/cat-weight-tracker-frontend:latest|${{ secrets.DOCKERHUB_USERNAME }}/cat-weight-tracker-frontend:latest|g" k8s/base/frontend.yaml
          
      - name: Apply Kubernetes manifests
        run: |
          # Apply all manifests using kustomize
          kubectl apply -k k8s/base/
          
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/backend -n cat-weight-tracker
          kubectl rollout status deployment/frontend -n cat-weight-tracker